### ISSUE TITLE
When PS2 servers are down, socket falls into reconnection loop, causing 100% CPU

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/aggregator#112]
https://i.imgur.com/JpMvxzV.png

Need to add a backoff timeout delay so it doesn't continiously attempt to reconnect constantly

**Comment by microwavekonijn** [comment]
Resubscribe method is called every 10ms, basically ddosing the event stream.
- [ ] Find out why it calls it so many times(expected behaviour should be every 15secs);
- [ ] Check if server is offline(gonna add a new event to the ps2census lib for this).

**Comment by Maelstromeous** [comment]
Didn't happen during last update, closing.
