### ISSUE TITLE
Excessive queries to Census for the GainExperience events

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/aggregator#151]
We seem to be absolutely hammering census at the moment when we get a GainExperence event. We should implement some sort of "in flight" system where if we are already querying census, we "tag long" that request, get the response of it and return the CharacterManager request.

https://i.imgur.com/YiBWt51.png

@microwavekonijn any chance you could add some sort of query buffering system where if the same query is being requested multiple times that the package doesn't friendly DDOS census?

**Comment by microwavekonijn** [comment]
https://github.com/microwavekonijn/ps2census/issues/31

**Comment by Maelstromeous** [comment]
Awesome! :)

**Comment by Maelstromeous** [comment]
@microwavekonijn noticed that https://github.com/microwavekonijn/ps2census/issues/31 is closed, was this fixed or shitcanned?

**Comment by microwavekonijn** [comment]
Honestly I don't remember. Have to check tomorrow.

**Comment by microwavekonijn** [comment]
So looking at the code it only requests characters once using the `CharacterManager`. I was working on a RestManager to do the same for any request by calculating some hash, but that is very much a work in progress.

**Comment by Maelstromeous** [comment]
Great, I'll close this then as it sounds like the original issue was fixed.
