### ISSUE TITLE
Implement Census Retry

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/aggregator#174]
So `c:retry` is a bag of dicks, it doesn't seem to work as intended. We need to add our own retry mechanism into there, try a query at least 3 times, then if that still totally fails then throw an exception.

**Comment by microwavekonijn** [comment]
Retry was already enabled from the start, my update just disabled it as I thought it was disabled by default(even though I should know better). But this functionality is planned for ps2census, I just need to know where I left all my time

**Comment by Maelstromeous** [comment]
Np, I'll get something rough together until you finalize it in the package
