### ISSUE TITLE
Implement latest ps2census version

### ISSUE THREAD

**Issue by Maelstromeous** [ps2alerts/aggregator#185]
Some key fixes have gone into the latest ps2census version, we need to integrate.

**Comment by Maelstromeous** [comment]
Blocked upgrading to V1.0.1 due to typehinting oddities within ps2census. @microwavekonijn is aware and is reviewing next steps.

**Comment by Maelstromeous** [comment]
This is should no longer be blocked since @microwavekonijn has made a v2.0, with fixes to the typehinting.

**Comment by microwavekonijn** [comment]
It is finished. Though there are some instances where I have to add type hinting where it now resolves to any, though such an update will not break anything.

**Comment by Maelstromeous** [comment]
Nice! Lets sync up at some point and go over how to implement this, as I've been meaning to do it for ages and the typehinting stuff broke me at the time.
